[install]
is_configured = 0

[ui]
is_visible = 1
label = Gemini SOC Assistant
setup_view = setup_page_dashboard

[launcher]
author = Rivan Nur
description = Integrasi Gemini AI untuk analisis SOC.
version = 1.0.0