[admin:gemini_endpoint]
match = /gemini_setup
members = gemini_settings

[admin_external:gemini_settings]
handlertype = python
python.version = python3
handlerfile = setup_handler.py
handlerexec = setup_handler.py