[geminianalyze-command]
syntax = geminianalyze prompt=<string> (field=<string>)? (model=<string>)? (batch=<bool>)? (role=<string>)?
shortdesc = Menganalisis log keamanan menggunakan Google AI.
description = Mengirimkan log event ke Google Gemini / Gemma untuk dianalisis. \nParameter wajib: 'prompt'. \nParameter opsional:\n - field (default: _raw)\n - model (override konfigurasi default)\n - batch (default: false. Ubah ke true untuk menganalisis multi-log secara kolektif)\n - role (override instruksi AI spesifik).
usage = public
example1 = index=firewall | head 5 | geminianalyze prompt="Jelaskan teknik apa yang digunakan IP ini" batch=false role="network_analyst"
comment1 = Menganalisis 5 log secara per-baris menggunakan kepribadian 'network_analyst'.
tags = gemini, ai, soc, security, analysis